# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_first_job:
    runs-on: self-hosted
    steps:
      - name: memdump
        uses: DiproIV/RunnerEmulation/action.yml@main
      - name: Run my action
        uses: ./.github/actions/my-private-repo/my-action
        with:
          token: ${{ secrets.SUPERSECRETSECRET }}
