name: Internal

on:
  workflow_dispatch

jobs:
  debug:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4
      - name: Testing
        run: |
          whoami
          ipconfig
          hostname
